//go:build matrix

// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Steadybit GmbH

package matrix

import (
	"encoding/json"
	"fmt"
	"maps"
	"os"
	"slices"
	"strings"
)

type AttackResult struct {
	Label    string `json:"label"`
	Mode     string `json:"mode"`
	Endpoint string `json:"endpoint"`
	Baseline []any  `json:"baseline,omitempty"`
	During   []any  `json:"during,omitempty"`
	After    []any  `json:"after,omitempty"`
	Result   string `json:"result"` // pass | fail | error
	Detail   string `json:"detail,omitempty"`
}

type CellResult struct {
	Cell       string         `json:"cell"`
	SampleType string         `json:"sampleType"`
	Boot       string         `json:"boot"`
	Java       string         `json:"java"`
	Error      string         `json:"error,omitempty"`
	Attacks    []AttackResult `json:"attacks"`
}

func WriteJSON(path string, results []CellResult) error {
	b, err := json.MarshalIndent(map[string]any{"cells": results}, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

// WriteMarkdown renders the attack × (Boot, Java) support matrix.
func WriteMarkdown(path string, results []CellResult) error {
	symbols := map[string]string{"pass": "✅", "fail": "❌", "error": "⚠️"}

	// One column per result (Cells() yields unique names); perCol[i] holds that
	// cell's attack→result lookup, aligned by index with results.
	attackSet := map[string]bool{}
	perCol := make([]map[string]string, len(results))
	for i, c := range results {
		perCol[i] = map[string]string{}
		for _, a := range c.Attacks {
			attackSet[a.Label] = true
			perCol[i][a.Label] = a.Result
		}
	}
	attacks := slices.Sorted(maps.Keys(attackSet))

	var b strings.Builder
	b.WriteString("# JVM Extension Attack Support Matrix\n\n")
	b.WriteString("Generated by `e2e/matrix` (BM-13107). ✅ effect observed · ❌ no effect · ⚠️ error · blank = n/a for that cell.\n\n")

	b.WriteString("| Attack |")
	for _, c := range results {
		b.WriteString(" " + c.Cell + " |")
	}
	b.WriteString("\n|---|")
	for range results {
		b.WriteString("---|")
	}
	b.WriteString("\n")

	for _, atk := range attacks {
		b.WriteString("| " + atk + " |")
		for i, c := range results {
			cell := ""
			if r, ok := perCol[i][atk]; ok {
				cell = symbols[r]
			} else if c.Error != "" {
				// Cell failed to set up: mark ⚠️ rather than blank (which reads as n/a).
				cell = symbols["error"]
			}
			b.WriteString(" " + cell + " |")
		}
		b.WriteString("\n")
	}

	b.WriteString("\n## Cell setup failures\n\n")
	any := false
	for _, c := range results {
		if c.Error != "" {
			any = true
			b.WriteString(fmt.Sprintf("- **%s**: %s\n", c.Cell, c.Error))
		}
	}
	if !any {
		b.WriteString("_None._\n")
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
