vulnerabilities:
  - id: CVE-2025-69720
    statement: Wait for upstream fix in debian
    expired_at: 2026-09-01
  - id: CVE-2026-48962
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-32280
    statement: Wait for runc release with fix
    paths:
      - usr/sbin/runc
  - id: CVE-2026-32283
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-32281
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-33811
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-33814
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-39820
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-39836
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-42499
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-39825
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-42499
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-39823
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-39825
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-39826
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-42499
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-42496
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-8376
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-42497
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-9538
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-42504
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-48959
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-45447
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-11822
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-11824
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
