vulnerabilities:
  - id: CVE-2025-69720
    statement: Wait for upstream fix in debian
    expired_at: 2026-09-01
  - id: CVE-2026-32280
    statement: Wait for runc release with fix
    paths:
      - usr/sbin/runc
  - id: CVE-2026-32283
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-32281
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-33811
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-33814
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-39820
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-39836
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
  - id: CVE-2026-42499
    statement: waiting for runc release
    expired_at: 2026-09-01
    paths:
      - usr/sbin/runc
