# syntax=docker/dockerfile:1

##
## Build GO binary
##
FROM golang:1.20-bullseye

ARG NAME
ARG VERSION
ARG REVISION

WORKDIR /app

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends build-essential
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN mkdir -p /opt/steadybit/extension

RUN go build \
    -gcflags="all=-N -l"\
    -ldflags="\
    -X 'github.com/steadybit/extension-kit/extbuild.ExtensionName=${NAME}' \
    -X 'github.com/steadybit/extension-kit/extbuild.Version=${VERSION}' \
    -X 'github.com/steadybit/extension-kit/extbuild.Revision=${REVISION}'" \
    -o /opt/steadybit/extension/extension \
    ${ADDITIONAL_BUILD_PARAMS}

RUN go install github.com/go-delve/delve/cmd/dlv@latest


ARG USERNAME=steadybit
ARG USER_UID=10000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends libcap2-bin \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*


COPY javaagents/download/target/javaagent /opt/steadybit/extension/javaagent
COPY debug.sh /opt/steadybit/extension/debug.sh
RUN chmod +x /opt/steadybit/extension/debug.sh
RUN chown -R $USERNAME:$USERNAME /opt/steadybit/extension
RUN setcap "cap_setuid,cap_setgid,cap_sys_admin,cap_dac_override+eip" /opt/steadybit/extension/extension
USER $USERNAME

WORKDIR /opt/steadybit/extension


ENV STEADYBIT_EXTENSION_JAVA_AGENT_PATH=/opt/steadybit/extension/javaagent
EXPOSE 8085 8081 40000
ENTRYPOINT ["/opt/steadybit/extension/debug.sh"]
