apiVersion: v2
name: steadybit-extension-jvm
description: Steadybit scaffold extension Helm chart for Kubernetes.
version: 1.0.4
appVersion: latest
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: ansgar.schulte@steadybit.com
    name: ansgarschulte
sources:
  - https://github.com/steadybit/extension-jvm
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: Steadybit website
      url: https://www.steadybit.com
    - name: Steadybit reliability hub
      url: https://hub.steadybit.com
dependencies:
  - name: extensionlib
    version: 1.2.2
    repository: https://steadybit.github.io/helm-charts
